schema_version: 1

context:
  name: itslive
  version: 0.7.2
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/itslive-${{ version }}.tar.gz
  sha256: 8563845b4f9fea266149a02274026d9a84fdc4580fd9bcadcb9540e7a8c0e9f1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - itslive-export = itslive.cli.export:export
      - itslive-plot = itslive.cli.plot:plot
      - itslive-search = itslive.cli.search:search

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - boto3 >=1.28
    - earthaccess >=0.5
    - h3-py >=4.0
    - matplotlib-base >=3.6
    - pandas >=1.5
    - plotext >=0
    - pqdm >=0.2
    - pyarrow >=10
    - pyproj >=3.4
    - pystac-client >=0.7
    - python >=${{ python_min }}
    - python-duckdb >=0.8
    - requests >=2.28
    - rich-click >=1.5
    - rustac >=0.9
    - s3fs >=2022.3
    - shapely >=2.0
    - tabulate >=0.9
    - xarray >=2022.6
    - zarr >=2.12
    - arro3-core >=0.6
tests:
  - python:
      imports:
        - itslive
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - itslive-export --help
      - itslive-plot --help
      - itslive-search --help

about:
  homepage: https://nasa-jpl.github.io/itslive-py/
  repository: https://github.com/nasa-jpl/itslive-py
  summary: Python client for ITSLIVE glacier velocity data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - betolink
    - jhkennedy
    - weiji14
